# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

price_tier(0)
submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})
precheck_include_in_app_purchases(false)
app_rating_config_path("./fastlane/metadata/app_store_rating_config.json")

ipa("./fastlane/builds/Flashcard Adder.ipa")

submit_for_review(true)
automatic_release(false)